### model params
Model:
  in_channels: 1
  out_channels: 1
  model_channels: 64
  param_dim: 7
  obj_dim: 2
  param_hidden_dim: 64
  obj_hidden_dim: 32
  attention_resolutions: [8, 16, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

ModelPredictor:
  in_channels: 1
  model_channels: 64
  param_dim: 7
  param_hidden_dim: 64
  obj_dim: 2
  attention_resolutions: [8, 16, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

### dataset params
Dataset:
  # parameters for torch.utils.data.DataLoader
  batch_size: 64
  shuffle: True
  drop_last: True
  pin_memory: True
  num_workers: 4
  image_size: [ 128, 128 ]
  param_dim: 8
  # The save path for data.
  datafilepath: "./dataset/batch_1_diff_corr_1.pkl"

### trainer params
Trainer:
  # sample time steps
  T: 1000
  beta: [0.0001, 0.02]


### callback params
Callback:
  # The save path for checkpoint.
  filepath: "./checkpoint/unet.pth"
  # Frequency of checkpoint saving.
  save_freq: 1

### callback params
CallbackPredictor:
  # The save path for checkpoint.
  filepath: "./predictor/unet.pth"
  # Frequency of checkpoint saving.
  save_freq: 1


### train params
device: "cuda"
epochs: 700
predictor_epochs: 700
# Whether to continue training, True or False
consume: False
# If continue training, which checkpoint to load
#consume_path: "./checkpoint/cifar10.pth"

### optimizer params
lr: 0.0002